In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt
import seaborn as sns
import re

In [2]:
data = pd.read_csv('sample_data_set_2 - Sheet1 (1).csv')

In [4]:
data.head()

,Date,App,Ad Group,State,Revenue,Ad Requests,Ad Responses,Fill Rate,Impressions,Render Rate,1st Clicks,2nd Clicks
0,08 Sep 2020,(SDK X) Cricket Mazza,Cricket Mazza Banner (AdX),Unresolved,0.0,3932330,3926253,99.9%,3849749,98.1%,10199,0
1,08 Sep 2020,(SDK X) Cricket Mazza,320x50,Unresolved,0.0,3932330,119,99.9%,118,99.2%,2,2
2,08 Sep 2020,(SDK X) Cricket Mazza,Dream11_320x50,Unresolved,0.0,3932330,96,99.9%,93,96.9%,2,2
3,08 Sep 2020,(SDK X) Cricket Mazza,My11_320x50,Unresolved,0.0,3932330,111,99.9%,110,99.1%,2,2
4,06 Sep 2020,(SDK X) Cricket Mazza,Cricket Mazza Banner (AdX),Unresolved,0.0,3839002,3834328,99.9%,3785127,98.7%,9492,0

## Q1

In [7]:
rev = data.groupby('App')[['Revenue','Ad Responses','Ad Requests','Impressions','1st Clicks','2nd Clicks']].sum()

In [13]:
rev.sort_values(by='Revenue', ascending = False)

,Revenue,Ad Responses,Ad Requests,Impressions,1st Clicks,2nd Clicks
App,,,,,,
Callbreak Multiplayer,869.40,131423691,2831311892,117137950,1092797,418077
Bottle Shooting Game,753.89,17484947,209701332,13112978,1121532,330501
World Cricket Championship 2,643.44,15099068,308410754,12068458,763675,149724
Traffic Bangalore: Check Fines,280.33,1728060,1791119,1011597,11955,2
World Cricket Championship Lt,145.27,1475191,17363413,1001420,170866,29033
...,...,...,...,...,...,...
Halloween Cars: Monster Race,0.00,0,2,0,0,0
Halloween Town Racing,0.00,0,1,0,0,0
Hey Flower,0.00,56,61,42,0,0
Hindi English Translator,0.00,900,1560,125,1,1
Zoo Craft : Blocky World Construction & Builder,0.00,2907,4265,2466,616,567

## Q4

In [17]:
data.groupby('Ad Group')[['Revenue']].sum().sort_values(by = 'Revenue')

                                        Revenue
Ad Group
test                                       0.00
Live Talk_Admob_MCM                        0.00
Latest Attitude Status 2020_Admob          0.00
Kannada Keyboard_Inmobi                    0.00
Jesus Wallpapers                           0.00
...                                         ...
Dream11_NonCore                          236.07
IPL banner                               260.04
Callbreak Multiplayer2_Inmobi_No Floor   264.99
MY11Circle_IN_SG_1500                    271.80
Bottle Shooting Game_Admob_ML            350.40

[188 rows x 1 columns]